# Generated by Django 4.1.2 on 2022-10-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0007_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vs1YkBaformsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('column_id', models.IntegerField()),
                ('settings', models.TextField()),
                ('custom', models.CharField(max_length=255)),
                ('options', models.TextField()),
                ('parent', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vs1yk_baforms_items',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='accomplished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='arrival_fee',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.JSONField(default=dict),
        ),
    ]
