# Generated by Django 4.1.2 on 2022-10-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0010_alter_order_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
