# Generated by Django 4.1.2 on 2023-02-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0013_applications_hired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='description_and_experience',
            new_name='desc_and_experience',
        ),
    ]
