# Generated by Django 4.1.2 on 2023-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0014_rename_description_and_experience_applications_desc_and_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='denied',
            field=models.BooleanField(default=False),
        ),
    ]
