# Generated by Django 4.1.2 on 2023-02-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0015_applications_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
