# Generated by Django 4.1.2 on 2023-02-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0017_applications_appointment_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='own_notes',
            field=models.TextField(blank=True),
        ),
    ]
