# Generated by Django 4.1.2 on 2023-02-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0019_alter_applications_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='created',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
