# Generated by Django 4.1.2 on 2023-02-20 15:48

from django.db import migrations, models
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0020_alter_applications_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('name_surname', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=20)),
                ('house_number', models.CharField(blank=True, max_length=20)),
                ('zip_code', models.CharField(max_length=20)),
                ('town', models.CharField(blank=True, max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('pesel', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('transport_form', models.CharField(max_length=255)),
                ('fuel_refund', models.SmallIntegerField(default=0.75)),
                ('account_number', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('signature', jsignature.fields.JSignatureField()),
            ],
        ),
    ]
