# Generated by Django 4.1.2 on 2023-02-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0022_order_managetool__type_1dda3b_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='ManageTool__type_1dda3b_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['type'], name='ManageTool__type_7cbee1_idx'),
        ),
    ]
