# Generated by Django 4.1.2 on 2023-02-23 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManageTool', '0024_remove_order_managetool__type_7cbee1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractemployment',
            name='bounded_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
