# Generated by Django 4.1.2 on 2023-02-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0025_contractemployment_bounded_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractemployment',
            name='fuel_refund',
            field=models.FloatField(default=0.75),
        ),
    ]
