# Generated by Django 4.1.2 on 2023-02-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0026_alter_contractemployment_fuel_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractemployment',
            name='fuel_refund',
            field=models.FloatField(blank=True, default=0.75, help_text='zł', null=True, verbose_name='Zwrot kosztów paliwa'),
        ),
    ]
