# Generated by Django 4.1.2 on 2023-02-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0027_alter_contractemployment_fuel_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractemployment',
            name='name_surname',
            field=models.CharField(max_length=255, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='signature_date',
            field=models.DateField(auto_created=True, auto_now_add=True, help_text='rrrr-mm-dd', verbose_name='Data podpisania'),
        ),
    ]
