# Generated by Django 4.1.2 on 2023-02-23 16:32

from django.db import migrations, models
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0029_contractemployment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractemployment',
            name='employer',
            field=models.CharField(choices=[(0, 'Rimarif Partners Sp. z o.o.')], default=0, max_length=255, verbose_name='Nazwa zamawiającego'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='hourly_rate_company_car',
            field=models.FloatField(default=85, help_text='zł brutto', verbose_name='Stawka godzinowa (samochód pracodawcy)'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='hourly_rate_own_car',
            field=models.FloatField(default=106, help_text='zł brutto', verbose_name='Stawka godzinowa (własny samochód)'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='visit_rate_company_car_firm',
            field=models.FloatField(default=85, verbose_name='Stawka za wizytę w firmach (samochód pracoawcy)'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='visit_rate_company_car_private_10min',
            field=models.FloatField(default=45, verbose_name='Stawka za wizytę w prywatnych domach - 10min (samochód pracodawcy)'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='visit_rate_company_car_private_20min',
            field=models.FloatField(default=65, verbose_name='Stawka za wizytę w prywatnych domach - 20min (samochód pracodawcy)'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='visit_rate_company_car_private_30min',
            field=models.FloatField(default=85, verbose_name='Stawka za wizytę w prywatnych domach - 30min (samochód pracodawcy)'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='visit_rate_company_car_private_60min',
            field=models.FloatField(default=115, verbose_name='Stawka za wizytę w prywatnych domach - 60min (samochód pracodawcy)'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='visit_rate_own_car_firm',
            field=models.FloatField(default=100, verbose_name='Stawka za wizytę w firmach (własny samochód)'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='visit_rate_own_car_private_10min',
            field=models.FloatField(default=60, verbose_name='Stawka za wizytę w prywatnych domach - 10min (własny samochód)'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='visit_rate_own_car_private_20min',
            field=models.FloatField(default=80, verbose_name='Stawka za wizytę w prywatnych domach - 20min (własny samochód)'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='visit_rate_own_car_private_30min',
            field=models.FloatField(default=100, verbose_name='Stawka za wizytę w prywatnych domach - 30min (własny samochód)'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='visit_rate_own_car_private_60min',
            field=models.FloatField(default=130, verbose_name='Stawka za wizytę w prywatnych domach - 60min (własny samochód)'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numer konta bankowego'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='fuel_refund',
            field=models.FloatField(default=0.75, help_text='zł/km', verbose_name='Zwrot kosztów paliwa'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer mieszkania'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numer dowodu osobistego'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='name_surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='pesel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='signature',
            field=jsignature.fields.JSignatureField(blank=True, null=True, verbose_name='Podpis pracownika'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='signature_date',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True, verbose_name='Data podpisania'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer domu'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='transport_form',
            field=models.CharField(blank=True, choices=[(0, 'Transport własny'), (1, 'Transport pracodawcy')], max_length=255, null=True, verbose_name='Forma transportu'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='type',
            field=models.CharField(blank=True, choices=[(0, 'Umowa o dzieło stawka godzinowa'), (1, 'Umowa o dzieło stawka za wizytę')], max_length=255, null=True, verbose_name='Typ umowy'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kod pocztowy'),
        ),
    ]
