# Generated by Django 4.1.2 on 2023-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0030_contractemployment_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractemployment',
            name='employer',
            field=models.CharField(choices=[(0, 'Rimarif Partners Sp. z o.o.')], default='Rimarif Partners Sp. z o.o.', max_length=255, verbose_name='Nazwa zamawiającego'),
        ),
    ]
