# Generated by Django 4.1.2 on 2023-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0031_alter_contractemployment_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractemployment',
            name='signature_date',
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='created',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='Data podpisania'),
        ),
        migrations.AddField(
            model_name='contractemployment',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='Ostatnia edycja'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='employer',
            field=models.CharField(blank=True, choices=[('0', 'Rimarif Partners Sp. z o.o.')], default='0', max_length=255, null=True, verbose_name='Nazwa zamawiającego'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='transport_form',
            field=models.CharField(blank=True, choices=[('0', 'Transport własny'), ('1', 'Transport pracodawcy')], max_length=255, null=True, verbose_name='Forma transportu'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Umowa o dzieło stawka godzinowa'), ('1', 'Umowa o dzieło stawka za wizytę')], max_length=255, null=True, verbose_name='Typ umowy'),
        ),
    ]
