# Generated by Django 4.1.2 on 2023-02-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0032_remove_contractemployment_signature_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractemployment',
            name='created',
            field=models.DateField(auto_created=True, verbose_name='Utowrzono'),
        ),
    ]
