# Generated by Django 4.1.2 on 2023-02-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0033_alter_contractemployment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractemployment',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Utowrzono'),
        ),
    ]
