# Generated by Django 4.1.2 on 2023-02-26 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0035_contractemployment_signed_by_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractemployment',
            name='concluded_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zawarcia umowy'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(26), django.core.validators.MaxLengthValidator(26)], verbose_name='Numer konta bankowego'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='pesel',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='PESEL'),
        ),
    ]
