# Generated by Django 4.1.2 on 2023-06-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0036_contractemployment_concluded_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractemployment',
            name='employer',
            field=models.IntegerField(blank=True, choices=[(0, 'Rimarif Partners Sp. z o.o.')], default='Rimarif Partners Sp. z o.o.', null=True, verbose_name='Nazwa zamawiającego'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='transport_form',
            field=models.IntegerField(blank=True, choices=[(0, 'Transport własny'), ('1', 'Transport pracodawcy')], null=True, verbose_name='Forma transportu'),
        ),
        migrations.AlterField(
            model_name='contractemployment',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Umowa o dzieło stawka godzinowa'), (1, 'Umowa o dzieło stawka za wizytę')], null=True, verbose_name='Typ umowy'),
        ),
    ]
