# Generated by Django 4.1.2 on 2023-06-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0037_alter_contractemployment_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'mazowieckie'), (1, 'pomorskie'), (2, 'małopolskie'), (3, 'lubuskie'), (4, 'dolnośląskie'), (5, 'małopolskie'), (6, 'wielkopolskie'), (7, 'śląskie'), (8, 'kujawsko-pomorskie'), (9, 'lubelskie'), (10, 'opolskie'), (11, 'podkarpackie'), (12, 'warmińsko-mazurskie'), (13, 'zachodniopomorskie'), (14, 'łódzkie'), (15, 'podlaskie')], max_length=50)),
            ],
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='ManageTool__type_d8e216_idx',
            old_name='ManageTool__type_1dda3b_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ManageTool.province', verbose_name='Województwo'),
        ),
    ]
