# Generated by Django 4.1.2 on 2023-06-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0038_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageTool.province', verbose_name='Województwo'),
        ),
    ]
