# Generated by Django 4.1.2 on 2023-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0039_alter_order_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.IntegerField(choices=[(0, 'mazowieckie'), (1, 'pomorskie'), (2, 'małopolskie'), (3, 'lubuskie'), (4, 'dolnośląskie'), (5, 'małopolskie'), (6, 'wielkopolskie'), (7, 'śląskie'), (8, 'kujawsko-pomorskie'), (9, 'lubelskie'), (10, 'opolskie'), (11, 'podkarpackie'), (12, 'warmińsko-mazurskie'), (13, 'zachodniopomorskie'), (14, 'łódzkie'), (15, 'podlaskie')], max_length=50),
        ),
    ]
