# Generated by Django 4.1.2 on 2023-06-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTool', '0043_alter_order_arrival_fee_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractemployment',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numer telefonu'),
        ),
    ]
